"""initial models

Revision ID: 534e861845d0
Revises: 
Create Date: 2026-03-25 23:32:50.164218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '534e861845d0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###